# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ruby_tweaks"
  s.version = "0.0.20"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["CHIKURA Shinsaku"]
  s.date = "2012-03-19"
  s.description = "Adds some tweak methods."
  s.email = "shinsaku@chikura.me"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/array_map_with_index_tweak.rb",
    "lib/array_refmap_tweak.rb",
    "lib/file_digest_tweak.rb",
    "lib/hash_from_json_tweak.rb",
    "lib/hash_pathable_tweak.rb",
    "lib/hash_remap_keys_tweak.rb",
    "lib/hash_with_default_tweak.rb",
    "lib/object_class_config_tweak.rb",
    "lib/ruby_tweaks.rb",
    "test/files/root1/config/class_config.yml",
    "test/files/root1/config/class_configs/poo.yml",
    "test/files/root2/config/class_configs/poo2.yml",
    "test/files/root2/config/class_configs/poo3.yml",
    "test/files/root2/config/class_configs/poo4.yml",
    "test/files/root3/config/class_configs/poo2.yml",
    "test/files/root3/config/class_configs/poo3.yml",
    "test/files/root3/config/class_configs/poo4.yml",
    "test/helper.rb",
    "test/test_ruby_tweaks.rb"
  ]
  s.homepage = "http://github.com/chsh/ruby_tweaks"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Adds some tweak methods."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<active_support>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<active_support>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<active_support>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

